acquisition:
  exposure_time_s: 0.001
  gain: 100
  interval_s: 0.001
  duration_s: 360   # Set to 0 for manual stop, positive int for duration in seconds

motor:
  base_path: "/home/declan/drone-project/ground/"
  spin_rate: 250

processing:
  jobs: 0            # 0 => auto (cpu_count-1)
  make_fits: true
  make_color: false
  make_green: false
  quiet: false

plotting:
  counts_per_rev: 2400
  debug: false
  time_offset_hours: null  # number or null